name: Validate Pull Request Title
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  validate-pr-title:
    runs-on: ubuntu-20.04
    steps:
      - name: Validate pull request title
        env:
          title: ${{ github.event.pull_request.title }}
          pattern: '^\[[A-Z]+-[\d]+\] '
        run: |
          if [[ $(echo "$title" | grep -cP "$pattern") -eq 0 ]]; then
            echo 'Warning: The pull request title does not match the naming convention!'
            echo 'Example: "[BPA-123] My awesome pull request"'
            exit 1
          fi
