name: GitHub Actions Demo
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  Validate-PR:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Title - ${{ github.event.pull_request.title }}"
      - run: echo "${{ github.event.pull_request.title }}" | grep -P '^\[[A-Z]+-[\d]+\] .*'
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^\[[A-Z]+-[\d]+\] .*'
