name: GitHub Actions Demo
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  Validate-PR:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^\[[A-Z]+-[\d]+\] .*'
